version: '2'
services:
  web:
    build: .
    command: npm run start:dev
    volumes:
      - ../:/usr/app/
    ports:
      - "3000:3000"
    links:
      - db
  db:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - "3306:3306"
  adminer:
    image: adminer
    ports:
      - "8080:8080"
    links:
      - db
  redis:
    image: redis:3
